//
//  ContentView.swift
//  ConduitTodoDemo
//
//  Created by Colin Ryan on 11/26/25.
//

import SwiftUI
import TodoShared

struct ContentView: View {
    // API Client - generated by @RPC macro
    let api = TodoAPIClient.live(baseUrl: "http://127.0.0.1:8080")

    // State
    @State private var todos: [Todo] = []
    @State private var newTodoTitle: String = ""
    @State private var filter: TodoFilter = .all
    @State private var isLoading: Bool = false
    @State private var errorMessage: String?
    @State private var showError: Bool = false

    enum TodoFilter: String, CaseIterable {
        case all = "All"
        case active = "Active"
        case completed = "Completed"

        var queryValue: String? {
            switch self {
            case .all: return nil
            case .active: return "false"
            case .completed: return "true"
            }
        }
    }

    var filteredTodos: [Todo] {
        switch filter {
        case .all:
            return todos
        case .active:
            return todos.filter { !$0.completed }
        case .completed:
            return todos.filter { $0.completed }
        }
    }

    var body: some View {
        NavigationStack {
            VStack(spacing: 0) {
                // Header Stats
                HStack(spacing: 20) {
                    StatCard(
                        title: "Total",
                        count: todos.count,
                        icon: "list.bullet",
                        color: .blue
                    )
                    StatCard(
                        title: "Active",
                        count: todos.filter { !$0.completed }.count,
                        icon: "circle",
                        color: .orange
                    )
                    StatCard(
                        title: "Done",
                        count: todos.filter { $0.completed }.count,
                        icon: "checkmark.circle.fill",
                        color: .green
                    )
                }
                .padding()

                // Filter Picker
                Picker("Filter", selection: $filter) {
                    ForEach(TodoFilter.allCases, id: \.self) { filter in
                        Text(filter.rawValue).tag(filter)
                    }
                }
                .pickerStyle(.segmented)
                .padding(.horizontal)
                .onChange(of: filter) { _, _ in
                    Task { await loadTodos() }
                }

                Divider()
                    .padding(.vertical, 8)

                // Todo List
                if isLoading {
                    ProgressView()
                        .frame(maxWidth: .infinity, maxHeight: .infinity)
                } else if filteredTodos.isEmpty {
                    EmptyStateView(filter: filter)
                } else {
                    List {
                        ForEach(filteredTodos) { todo in
                            TodoRow(
                                todo: todo,
                                onToggle: { await toggleTodo(todo) }
                            )
                        }
                    }
                    .listStyle(.plain)
                }

                Divider()

                // Add Todo Input
                HStack {
                    TextField("New todo...", text: $newTodoTitle)
                        .textFieldStyle(.roundedBorder)
                        .onSubmit {
                            Task { await createTodo() }
                        }

                    Button(action: { Task { await createTodo() } }) {
                        Image(systemName: "plus.circle.fill")
                            .font(.title2)
                            .foregroundColor(.blue)
                    }
                    .disabled(newTodoTitle.isEmpty)
                }
                .padding()
                .background(Color(.systemBackground))
            }
            .navigationTitle("📝 Conduit Todo")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarTrailing) {
                    Button(action: { Task { await loadTodos() } }) {
                        Image(systemName: "arrow.clockwise")
                    }
                }
            }
            .alert("Error", isPresented: $showError) {
                Button("OK", role: .cancel) {}
            } message: {
                Text(errorMessage ?? "Unknown error")
            }
            .task {
                await loadTodos()
            }
        }
    }

    // MARK: - API Calls

    func loadTodos() async {
        isLoading = true
        errorMessage = nil

        do {
            todos = try await api.listTodos(completed: filter.queryValue, config: nil)
        } catch {
            errorMessage = "Failed to load todos: \(error.localizedDescription)"
            showError = true
        }

        isLoading = false
    }

    func createTodo() async {
        guard !newTodoTitle.isEmpty else { return }

        let title = newTodoTitle
        newTodoTitle = ""

        do {
            let request = CreateTodoRequest(title: title)
            let newTodo = try await api.createTodo(body: request, config: nil)

            // Optimistically add to list
            todos.insert(newTodo, at: 0)
        } catch {
            errorMessage = "Failed to create todo: \(error.localizedDescription)"
            showError = true
            newTodoTitle = title  // Restore on error
        }
    }

    func toggleTodo(_ todo: Todo) async {
        // Optimistic update
        if let index = todos.firstIndex(where: { $0.id == todo.id }) {
            todos[index] = Todo(
                id: todo.id,
                title: todo.title,
                completed: !todo.completed
            )
        }

        do {
            let request = UpdateTodoRequest(completed: !todo.completed)
            let updated = try await api.completeTodo(body: request, id: todo.id,  config: nil)

            // Update with server response
            if let index = todos.firstIndex(where: { $0.id == todo.id }) {
                todos[index] = updated
            }
        } catch {
            errorMessage = "Failed to update todo: \(error.localizedDescription)"
            showError = true

            // Revert on error
            if let index = todos.firstIndex(where: { $0.id == todo.id }) {
                todos[index] = todo
            }
        }
    }
}

// MARK: - Supporting Views

struct StatCard: View {
    let title: String
    let count: Int
    let icon: String
    let color: Color

    var body: some View {
        VStack(spacing: 4) {
            Image(systemName: icon)
                .font(.title2)
                .foregroundColor(color)
            Text("\(count)")
                .font(.title3)
                .bold()
            Text(title)
                .font(.caption)
                .foregroundColor(.secondary)
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 12)
        .background(color.opacity(0.1))
        .cornerRadius(12)
    }
}

struct TodoRow: View {
    let todo: Todo
    let onToggle: () async -> Void

    @State private var isToggling = false

    var body: some View {
        HStack {
            Button(action: {
                Task {
                    isToggling = true
                    await onToggle()
                    isToggling = false
                }
            }) {
                Image(systemName: todo.completed ? "checkmark.circle.fill" : "circle")
                    .font(.title3)
                    .foregroundColor(todo.completed ? .green : .gray)
            }
            .disabled(isToggling)

            Text(todo.title)
                .strikethrough(todo.completed)
                .foregroundColor(todo.completed ? .secondary : .primary)

            Spacer()

            if isToggling {
                ProgressView()
                    .scaleEffect(0.8)
            }
        }
        .padding(.vertical, 4)
        .contentShape(Rectangle())
        .onTapGesture {
            Task {
                isToggling = true
                await onToggle()
                isToggling = false
            }
        }
    }
}

struct EmptyStateView: View {
    let filter: ContentView.TodoFilter

    var body: some View {
        VStack(spacing: 16) {
            Image(systemName: emptyIcon)
                .font(.system(size: 60))
                .foregroundColor(.gray)

            Text(emptyMessage)
                .font(.title3)
                .foregroundColor(.secondary)

            Text(emptySubtitle)
                .font(.caption)
                .foregroundColor(.secondary)
                .multilineTextAlignment(.center)
        }
        .padding()
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    var emptyIcon: String {
        switch filter {
        case .all: return "tray"
        case .active: return "checkmark.circle"
        case .completed: return "star"
        }
    }

    var emptyMessage: String {
        switch filter {
        case .all: return "No todos yet"
        case .active: return "All done!"
        case .completed: return "No completed todos"
        }
    }

    var emptySubtitle: String {
        switch filter {
        case .all: return "Add your first todo below"
        case .active: return "You've completed all your todos"
        case .completed: return "Complete some todos to see them here"
        }
    }
}

#Preview {
    ContentView()
}
